CLOSE DATABASES ALL
SET EXCLUSIVE OFF
SET SAFETY OFF
SET DELETE ON

SELECT 0
USE "C:\ACS\initdata\cusmas01.DBF" SHARED ALIAS cus01

SELECT 0
USE "N:\apps\acss\cusmas.DBF" SHARED ALIAS cus02
INDEX ON ALLTRIM(fcustno) TO l
GO TOP

SELECT cus01
DO WHILE !EOF()
	SELECT cus02
	SEEK ALLTRIM(cus01.fcustno)
	IF FOUND()
		REPLACE cus02.cm_frst WITH cus01.cm_frst
		REPLACE cus02.fcclass WITH cus01.fcclass
	ENDIF
	SELECT cus01
	SKIP
ENDDO

CLOSE DATABASES ALL
RETURN
