*** Fix The Last Act. Date For Carroll Auto Sales ***
CLOSE DATABASES ALL
SET EXCLUSIVE OFF
SET SAFETY OFF
SET DELETE ON

SELECT 0
USE "N:\APPS\ACSS\psales01.DBF" SHARED ALIAS psl01
*SET FILTER TO ri_roinv = "S" .OR. ri_roinv = "I"
*BROW

SELECT 0
USE "N:\APPS\ACSS\pmast01.DBF" SHARED ALIAS pms02
INDEX ON ALLTRIM(pm_part) TO l
GO TOP

SELECT psl01
DO WHILE !EOF()
	SELECT pms02
	SEEK ALLTRIM(psl01.ri_part)
	IF FOUND()
		REPLACE pms02.pm_adate WITH psl01.ri_date
	ENDIF
	SELECT psl01
	SKIP
ENDDO

CLOSE DATABASES ALL
RETURN
