CLOSE DATABASES ALL
SET EXCLUSIVE OFF
SET SAFETY OFF
SET DELETE ON

SELECT 0
USE "C:\ACS\initdata\misspart01.DBF" SHARED ALIAS pmt03

SELECT 0
USE "C:\ACS\initdata\PMAST01.DBF"    SHARED ALIAS pmt02

SELECT 0
USE "N:\Apps\Acss\PMAST01.DBF"       SHARED ALIAS pmt01
INDEX ON ALLTRIM(pm_part) TO l
GO TOP

SELECT pmt02
DO WHILE !EOF()
	SELECT pmt01
	SEEK ALLTRIM(pmt02.pm_part)
	IF !FOUND()
		SELECT pmt02
		SCATTER TO c
		SELECT pmt01
		APPEND BLANK
		GATHER FROM c
		SELECT pmt03
		APPEND BLANK
		GATHER FROM c
	ENDIF
	SELECT pmt02
	SKIP
ENDDO

CLOSE DATABASES ALL
RETURN

