CLEAR
CLOSE DATABASES ALL
SET EXCLUSIVE OFF
SET SAFETY OFF

PRIVATE ival, oldcus, prvdate, m1, dflt_drive
dflt_drive = "\\acsserver\SUPPORT\APPS\HORNER\"

USE dflt_drive + "vinmas.DBF" IN 0
SELECT vinmas
GO TOP
DO WHILE !EOF()
	IF LEN(ALLTRIM(vi_vin)) = 17
		DO CASE
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'A'
				REPLACE vi_yr WITH '1980'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'B'
				REPLACE vi_yr WITH '1981'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'C'
				REPLACE vi_yr WITH '1982'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'D'
				REPLACE vi_yr WITH '1983'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'E'
				REPLACE vi_yr WITH '1984'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'F'
				REPLACE vi_yr WITH '1985'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'G'
				REPLACE vi_yr WITH '1986'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'H'
				REPLACE vi_yr WITH '1987'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'J'
				REPLACE vi_yr WITH '1988'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'K'
				REPLACE vi_yr WITH '1989'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'L'
				REPLACE vi_yr WITH '1990'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'M'
				REPLACE vi_yr WITH '1991'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'N'
				REPLACE vi_yr WITH '1992'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'P'
				REPLACE vi_yr WITH '1993'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'R'
				REPLACE vi_yr WITH '1994'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'S'
				REPLACE vi_yr WITH '1995'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'T'
				REPLACE vi_yr WITH '1996'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'V'
				REPLACE vi_yr WITH '1997'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'W'
				REPLACE vi_yr WITH '1998'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'X'
				REPLACE vi_yr WITH '1999'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'Y'
				REPLACE vi_yr WITH '2000'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  '1'
				REPLACE vi_yr WITH '2001'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  '2'
				REPLACE vi_yr WITH '2002'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  '3'
				REPLACE vi_yr WITH '2003'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  '4'
				REPLACE vi_yr WITH '2004'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  '5'
				REPLACE vi_yr WITH '2005'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  '6'
				REPLACE vi_yr WITH '2006'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  '7'
				REPLACE vi_yr WITH '2007'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  '8'
				REPLACE vi_yr WITH '2008'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  '9'
				REPLACE vi_yr WITH '2009'
		ENDCASE
	ENDIF
	SKIP
ENDDO
CLOSE DATA ALL

USE dflt_drive + "masold01.DBF" IN 0
SELECT masold01
GO TOP
DO WHILE !EOF()
	IF LEN(ALLTRIM(vi_vin)) = 17
		DO CASE
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'A'
				REPLACE vi_yr WITH '1980'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'B'
				REPLACE vi_yr WITH '1981'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'C'
				REPLACE vi_yr WITH '1982'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'D'
				REPLACE vi_yr WITH '1983'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'E'
				REPLACE vi_yr WITH '1984'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'F'
				REPLACE vi_yr WITH '1985'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'G'
				REPLACE vi_yr WITH '1986'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'H'
				REPLACE vi_yr WITH '1987'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'J'
				REPLACE vi_yr WITH '1988'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'K'
				REPLACE vi_yr WITH '1989'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'L'
				REPLACE vi_yr WITH '1990'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'M'
				REPLACE vi_yr WITH '1991'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'N'
				REPLACE vi_yr WITH '1992'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'P'
				REPLACE vi_yr WITH '1993'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'R'
				REPLACE vi_yr WITH '1994'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'S'
				REPLACE vi_yr WITH '1995'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'T'
				REPLACE vi_yr WITH '1996'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'V'
				REPLACE vi_yr WITH '1997'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'W'
				REPLACE vi_yr WITH '1998'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'X'
				REPLACE vi_yr WITH '1999'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  'Y'
				REPLACE vi_yr WITH '2000'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  '1'
				REPLACE vi_yr WITH '2001'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  '2'
				REPLACE vi_yr WITH '2002'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  '3'
				REPLACE vi_yr WITH '2003'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  '4'
				REPLACE vi_yr WITH '2004'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  '5'
				REPLACE vi_yr WITH '2005'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  '6'
				REPLACE vi_yr WITH '2006'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  '7'
				REPLACE vi_yr WITH '2007'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  '8'
				REPLACE vi_yr WITH '2008'
			CASE SUBSTR(ALLTRIM(vi_vin),10,1) =  '9'
				REPLACE vi_yr WITH '2009'
		ENDCASE
	ENDIF
	SKIP
ENDDO
CLOSE DATA ALL

USE dflt_drive + "romast01.DBF" IN 0
SELECT romast01
GO TOP
DO WHILE !EOF()
	IF LEN(ALLTRIM(rm_vin)) = 17
		DO CASE
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'A'
				REPLACE rm_year WITH '1980'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'B'
				REPLACE rm_year WITH '1981'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'C'
				REPLACE rm_year WITH '1982'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'D'
				REPLACE rm_year WITH '1983'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'E'
				REPLACE rm_year WITH '1984'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'F'
				REPLACE rm_year WITH '1985'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'G'
				REPLACE rm_year WITH '1986'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'H'
				REPLACE rm_year WITH '1987'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'J'
				REPLACE rm_year WITH '1988'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'K'
				REPLACE rm_year WITH '1989'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'L'
				REPLACE rm_year WITH '1990'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'M'
				REPLACE rm_year WITH '1991'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'N'
				REPLACE rm_year WITH '1992'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'P'
				REPLACE rm_year WITH '1993'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'R'
				REPLACE rm_year WITH '1994'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'S'
				REPLACE rm_year WITH '1995'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'T'
				REPLACE rm_year WITH '1996'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'V'
				REPLACE rm_year WITH '1997'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'W'
				REPLACE rm_year WITH '1998'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'X'
				REPLACE rm_year WITH '1999'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'Y'
				REPLACE rm_year WITH '2000'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  '1'
				REPLACE rm_year WITH '2001'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  '2'
				REPLACE rm_year WITH '2002'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  '3'
				REPLACE rm_year WITH '2003'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  '4'
				REPLACE rm_year WITH '2004'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  '5'
				REPLACE rm_year WITH '2005'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  '6'
				REPLACE rm_year WITH '2006'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  '7'
				REPLACE rm_year WITH '2007'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  '8'
				REPLACE rm_year WITH '2008'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  '9'
				REPLACE rm_year WITH '2009'
		ENDCASE
	ENDIF
	SKIP
ENDDO
CLOSE DATA ALL

USE dflt_drive + "hmast01.DBF" IN 0
SELECT hmast01
GO TOP
DO WHILE !EOF()
	IF LEN(ALLTRIM(rm_vin)) = 17
		DO CASE
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'A'
				REPLACE rm_year WITH '1980'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'B'
				REPLACE rm_year WITH '1981'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'C'
				REPLACE rm_year WITH '1982'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'D'
				REPLACE rm_year WITH '1983'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'E'
				REPLACE rm_year WITH '1984'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'F'
				REPLACE rm_year WITH '1985'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'G'
				REPLACE rm_year WITH '1986'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'H'
				REPLACE rm_year WITH '1987'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'J'
				REPLACE rm_year WITH '1988'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'K'
				REPLACE rm_year WITH '1989'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'L'
				REPLACE rm_year WITH '1990'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'M'
				REPLACE rm_year WITH '1991'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'N'
				REPLACE rm_year WITH '1992'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'P'
				REPLACE rm_year WITH '1993'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'R'
				REPLACE rm_year WITH '1994'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'S'
				REPLACE rm_year WITH '1995'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'T'
				REPLACE rm_year WITH '1996'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'V'
				REPLACE rm_year WITH '1997'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'W'
				REPLACE rm_year WITH '1998'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'X'
				REPLACE rm_year WITH '1999'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  'Y'
				REPLACE rm_year WITH '2000'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  '1'
				REPLACE rm_year WITH '2001'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  '2'
				REPLACE rm_year WITH '2002'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  '3'
				REPLACE rm_year WITH '2003'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  '4'
				REPLACE rm_year WITH '2004'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  '5'
				REPLACE rm_year WITH '2005'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  '6'
				REPLACE rm_year WITH '2006'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  '7'
				REPLACE rm_year WITH '2007'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  '8'
				REPLACE rm_year WITH '2008'
			CASE SUBSTR(ALLTRIM(rm_vin),10,1) =  '9'
				REPLACE rm_year WITH '2009'
		ENDCASE
	ENDIF
	SKIP
ENDDO

CLOSE DATA ALL
RETURN